# Generated by Django 5.2 on 2025-05-23 05:49

import myuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='C:\\Users\\Jhay\\OneDrive\\Desktop\\projects\\socmed\\backend\\media\\users/profile/default/avatar.png', null=True, upload_to=myuser.models.upload_to),
        ),
    ]
