# Generated by Django 5.2 on 2025-05-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_user_gender_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=20, null=True),
        ),
    ]
