# Generated by Django 5.2 on 2025-06-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staatus',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='Offline', max_length=20),
        ),
    ]
